---
title: "Pretest Analysis"
author: "Nicolas Restrepo"
date: "11/1/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Analysis 

```{r}

library(tidyverse)
theme_set(theme_light())
```


```{r}

# Load the data in 

data <- read_csv("pretest.csv")

# Get rid of the first three rows which are uninformative 

data <- data[-(1:3), ]

```

Let's find out who passed the attention checks 

```{r}

data <- data %>% 
  mutate(passed_1 = ifelse(ach_1_1 == "extremely harmful", 1, 0), 
         passed_2 = ifelse(ach_2_1 == "not at all immoral", 1, 0), 
         passed_3 = ifelse(ach_3_1 == "moderately unexpected", 1, 0), 
         passed_4 = ifelse(ach_4_1 == "not at all harmful", 1, 0), 
         passed_5 = ifelse(ach_5_1 == "extremely immoral", 1, 0), 
         passed_6 = ifelse(ach_6_1 == "extremely unexpected", 1, 0), 
         sum_pass = passed_1 + passed_2 + passed_3 + passed_4 + passed_5 + passed_6)
```

Let's just get a table to know who passed the attention checks 

```{r}

table_passed <- data %>% 
  select(PID, sum_pass)

```

Let's recode the data so we get numbers instead of labels

```{r}

# Mutate all main questions 

data_recoded <- data %>% 
  mutate_at(vars(contains("_h_1")), funs(recode(., 
                                   "not at all harmful" = 1, 
                                   "slightly harmful" = 2, 
                                   "moderately harmful" = 3, 
                                   "very harmful" = 4, 
                                   "extremely harmful" = 5))) %>% 
  mutate_at(vars(contains("_i_1")), funs(recode(., 
                                   "not at all immoral" = 1, 
                                   "slightly immoral" = 2, 
                                   "moderately immoral" = 3, 
                                   "very immoral" = 4, 
                                   "extremely immoral" = 5))) %>% 
  mutate_at(vars(contains("_u_1")), funs(recode(., 
                                   "not at all unexpected" = 1, 
                                   "slightly unexpected" = 2, 
                                   "moderately unexpected" = 3, 
                                   "very unexpected" = 4, 
                                   "extremely unexpected" = 5)))
  
  
```

Let's try to get a more trim data set 

```{r}

# Get of of the first set of uninformative columns 

data_recoded <- data_recoded %>% 
  select(-contains("ach")) %>% 
  select(pkp_h_1:msas_u_1)

# Now let's create a more amenable dataset 

d <- data_recoded %>% 
  mutate(id = 1:n()) %>% 
  select(id, everything()) 

# Rename all variables 

d <- d %>%  
  rename_all(
    funs(str_remove(., "_1"))
    ) %>% 
  mutate_if(is.character, as.numeric)

# create a summary table for the values of each question 

gd <- d %>% 
  select(-id) %>% 
  gather(key = "scenario", 
         value = "score") %>% 
  group_by(scenario) %>% 
  summarise_all(funs(avg = mean(.), maximum = max(.), minimum = min(.), st_dv = sd(.))) %>% 
  mutate(ci_lower = avg - 1.96*st_dv, 
         ci_upper = avg + 1.96*st_dv)
  
```

Now, we are in a position to start making some summary plots 

```{r}

# Keep only harm questions 

gdh <- gd[str_which(gd$scenario, "_h"),]

# Plot harm questions 

gdh %>% 
  ggplot(aes(x = reorder(scenario, avg), y = avg)) + 
  geom_point(col = "darkred", fill = "darkred") + 
  geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), pch = 0) +
  coord_flip() + 
  labs(x = "", 
       y = "Ratings", 
       title = "Perceptions of Harmfulness")

# Now lets look at immorality 

gdi <- gd[str_which(gd$scenario, "_i"),]

# Plot immorality

gdi %>% 
  ggplot(aes(x = reorder(scenario, avg), y = avg)) + 
  geom_point(col = "darkred", fill = "darkred") + 
  geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), pch = 0) +
  coord_flip() + 
  labs(x = "", 
       y = "Ratings", 
       title = "Perceptions of Immorality")

# Lastly let's look at unexpectedness 

gdu <- gd[str_which(gd$scenario, "_u"),]

# Plot Unexpectedness

gdu %>% 
  ggplot(aes(x = reorder(scenario, avg), y = avg)) + 
  geom_point(col = "darkred", fill = "darkred") + 
  geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), pch = 0) +
  coord_flip() + 
  labs(x = "", 
       y = "Ratings", 
       title = "Perceptions of Unexpectedness")

```



