---
title: "Covering the Semantic Space"
author: "Nicolas Restrepo"
date: "12/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## A principled way of approaching semantic variation

One of the challenges, at this point, is to come up with a way to explore the semantic differences between the events in a systematic way. A possible way to do this is to pick one scenario per foundation and systematically vary the components in which we are most interested. Our previous analyses suggest that we should focus on variations on the behavior's evaluation and the object's potency. We could explore movements along these axes by creating five iterations of the same action. Let's say we pick the event: 

- A person dates (2.24, 1.53, 0.75) their cousin.

To explore variations in the behavior, we create a similar (but much more positive example): 
- A person makes love to (3.14, 2.79, 1.08) their cousin. 

And a similar but more negative one: 

- A person has an affair with (-3.26, 0.61, 0.11)

Now, to explore variations in the object's potency we can add modifiers to the word cousin. 

- A person dates their shy cousin (0.26  -0.59  -0.62)

- A person dates their outgoing cousin (1.61 0.92 1.57)

For this trangression, then, we would have a total of 5 scenarios: the baseline, the two behaviors modifications, and the two object modifications. 


