---
title: "Selected Scenarios"
author: "Nicolas Restrepo"
date: "10/17/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Translations of Selected Scenario 


```{r}

library(tidyverse)
library(haven)
library(readxl)
theme_set(theme_light())
```

First let me load the equation created by Emily 

```{r}

#load equation information from Interact
equation <- read_table("equation info.txt", col_names = FALSE)
equation<- as.data.frame(equation) #put in better format

#label according to what term the coefficients correspond to
colnames(equation) <- c("Term", "Aep", "App", "Aap", "Bep", "Bpp", "Bap", "Oep", "Opp", "Oap")
rownames(equation) <- c("Constant", "Aeb", "Apb", "Aab", "Beb", "Bpb", "Bab", "Oeb", "Opb", "Oab",
                        "AeBe", "AeOp", "ApBp", "AaBa", "BeOe", "BeOp", "BpOe", "BpOp", "AeBeOe",
                        "AeBeOp")

#get rid of the Z000 column
equation <- equation[,-1]

#writing function
eventcalc <- function(actor, beh, object) {
  
  #make empty matrix to store info
  store <- matrix(NA, 20, 1)
  
  #something that won't affect the constant
  store[1,] <- 1
  
  #setting actor EPA values
  store[2,] <- subdictionary$E[subdictionary$term == actor] #Ae
  store[3,] <- subdictionary$P[subdictionary$term == actor] #Ap
  store[4,] <- subdictionary$A[subdictionary$term == actor] #Aa
  
  #setting subdictionary EPA values
  store[5,] <- subdictionary$E[subdictionary$term == beh] #Be
  store[6,] <- subdictionary$P[subdictionary$term == beh] #Bp
  store[7,] <- subdictionary$A[subdictionary$term == beh] #Ba
  
  #setting object EPA values
  store[8,] <- subdictionary$E[subdictionary$term == object] #Oe
  store[9,] <- subdictionary$P[subdictionary$term == object] #Op
  store[10,] <- subdictionary$A[subdictionary$term == object] #Oa
  
  store[11,] <- store[2,] * store[5,] #Ae*Be
  store[12,] <- store[2,] * store[9,] #Ae*Op
  store[13,] <- store[3,] * store[6,] #Ap*Bp
  store[14,] <- store[4,] * store[7,] #Aa*Ba
  store[15,] <- store[5,] * store[8,] #Be*Oe
  store[16,] <- store[5,] * store[9,] #Be*Op
  store[17,] <- store[6,] * store[8,] #Bp*Oe
  store[18,] <- store[6,] * store[9,] #Bp*Op
  store[19,] <- store[2,] * store[5,] * store[8,] #Ae*Be*Oe
  store[20,] <- store[2,] * store[5,] * store[9,] #Ae*Be*Op
  
  #to store the EPA values for actor, subdictionary, and object after situation
  postepa <- matrix(NA, 20, 9)
  
  #apply function 
  i<- 1
  for(i in 1:9) {
    postepa[,i] <- equation[,i]*store
    i+1
  }
  
  #put in better data format
  postepa <- as.data.frame(postepa)
  postepa <- apply(postepa, 2, sum) #get the sum of the equation to get the actual EPA values
  postepa <- cbind(store[2:10], postepa) #put the initial EPA and post EPA in df together
  
  #calculate deflection
  deflection <- apply(postepa, 1, diff) #get difference b/w pre and post EPA
  deflection <- as.data.frame(deflection)
  deflection <- sapply(deflection, function(x) x^2) #sq differences
  deflection <- apply(deflection, 2, sum) #sum squared differences :) 
  return(deflection)
}

```

Now let's get the dictionary in 

```{r}

dictionary <- read_csv("FullSurveyorUSMeans.csv")

subdictionary <- dictionary %>% 
  select(c(1:4, 11),)
```

Now let me load my own set of translations 

```{r}

translations <- read_excel("selected_translations.xlsx")
```

Let me try to get rid of the unecessary words in the dictionary 

```{r}
subdictionary <- subdictionary[-c(121,164, 518, 563, 1026, 2030, 2176), ]
```

Let add the words to the subdictionary first 

```{r}

new_identities <- read_excel("new_identities.xlsx") 

new_identities <- new_identities %>% 
  rename(term = Term)

subdictionary <- bind_rows(subdictionary, new_identities)
```

Calculate the deflections 

```{r}

selected_events <- translations %>% 
        mutate(actor = as.character(actor),
               object = as.character(object), 
               behavior = as.character(behavior)) %>% 
  rowwise %>% 
         mutate(def = eventcalc(actor, behavior, object))
```

Now let's create the visualization 

```{r}

selected_events <- selected_events %>% 
  mutate(event = paste(actor, behavior, object, sep = " ")) 

selected_events %>% 
  ggplot(aes(x = reorder(event, def), y = def)) + 
  geom_point(col = "darkred") + 
  coord_flip() + 
  facet_grid(type ~ . , scales = "free_y", space = "free") +
  labs(title = "Deflection of the Moral Scenarios", 
       y = " ", 
       x = "") + 
  theme(legend.position = "none") +
  theme_minimal(base_size = 10) 

ggsave("selected_events.png")
```

Save the dataset

```{r}

# Save 

write_csv(selected_events, "selected_events.csv")

```


